import * as z from 'zod';
import { ColumnDef } from '@tanstack/react-table';

export const invoiceSchema = z.object({
  accountName: z.string(),
  accountNumber: z.string(),
  statusName: z.string(),
  bankAccountTypeName: z.string(),
  bankName: z.string(),
  currencyCode: z.string(),
  currencyName: z.string(),
  balance: z.number(),
});

export type IInvoiceSchema = z.infer<typeof invoiceSchema>;

export const financeColumnDef: ColumnDef<IInvoiceSchema>[] = [
  {
    accessorKey: 'accountName',
    header: 'Account name',
  },
  {
    accessorKey: 'accountNumber',
    header: 'Account number',
  },
  {
    accessorKey: 'statusName',
    header: 'Status',
  },
  {
    accessorKey: 'bankAccountTypeName',
    header: 'Bank account type',
  },
  {
    accessorKey: 'bankName',
    header: 'Bank name',
  },
  {
    accessorKey: 'currencyCode',
    header: 'Currency code',
  },
  {
    accessorKey: 'currencyName',
    header: 'Currency name',
  },
  {
    accessorKey: 'balance',
    header: 'Balance',
  },
  // {
  //   accessorKey: 'invoiceDate',
  //   header: 'Invoice Date',
  //   cell({ row }) {
  //     const formatedDate = new Date(
  //       row.getValue('invoiceDate')
  //     ).toLocaleDateString('en-GB');
  //     return <div>{formatedDate}</div>;
  //   },
  // },
  // {
  //   accessorKey: 'dueDate',
  //   header: 'Due Date',
  //   cell({ row }) {
  //     const formatedDate = new Date(
  //       row.getValue('dueDate')
  //     ).toLocaleDateString('en-GB');
  //     return <div>{formatedDate}</div>;
  //   },
  // },
  // {
  //   accessorKey: 'currency',
  //   header: 'Currency',
  // },
  // {
  //   accessorKey: 'exchangeRate',
  //   header: 'Exchange Rate',
  // },
  // {
  //   accessorKey: 'client',
  //   header: 'Client',
  // },
  // {
  //   accessorKey: 'project',
  //   header: 'Project',
  // },
  // {
  //   accessorKey: 'calculateTax',
  //   header: 'Calculate Tax',
  // },
  // {
  //   accessorKey: 'bankAccount',
  //   header: 'Bank Account',
  // },
  // {
  //   accessorKey: 'billingAddress',
  //   header: 'Billing Address',
  // },
  // {
  //   accessorKey: 'shippingAddress',
  //   header: 'Shipping Address',
  // },
  // {
  //   accessorKey: 'generatedBy',
  //   header: 'Generated By',
  // },
];

export const bankAccountSchema = z.object({
  bankName: z.string(),
  accountHolderName: z.string(),
  accountNumber: z.string(),
  accountType: z.string(),
  currency: z.string(),
  contactNumber: z.string(),
  openingBalance: z.string(),
  status: z.string(),
});
export type IBankAccount = z.infer<typeof bankAccountSchema>;

export const bankAccountSchemaCash = z.object({
  cashAccountHolderName: z.string(),
  cashCurrency: z.string(),
  cashContactNumber: z.string(),
  cashOpeningBalance: z.string(),
  cashStatus: z.string(),
});
export type IBankAccountCash = z.infer<typeof bankAccountSchemaCash>;
