import Head from 'next/head';
import Sidebar, { SidebarItem } from '@/components/molecules/Sidebar';
import GridLayout from '@/components/molecules/GridLayout';
import { LifeBuoy,Receipt,Boxes,Package,UserCircle,BarChart3,LayoutDashboard,Settings } from 'lucide-react';


export default function Home() {
  return (
    <>
      <Head>
        <title>Arkiva</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full flex flex-row gap-4">
      <Sidebar/>
      <div className='max-w-[calc(100%-250px)]'>
        <h2 className='w-full bg-blue-200'>hello</h2>
        <GridLayout />
      </div>
      </main>
    </>
  );
}
