'use client';
import KpiCard from '@/components/atoms/KpiCard';
import Head from 'next/head';
import { useState } from 'react';

import dynamic from 'next/dynamic';

const NoSSR = dynamic(() => import('../pages/dashboard'), {
  ssr: false,
});
const cities = [
  {
    name: 'New York',
    sales: 9800,
  },
  {
    name: 'London',
    sales: 4567,
  },
  {
    name: 'Hong Kong',
    sales: 3908,
  },
  {
    name: 'San Francisco',
    sales: 2400,
  },
  {
    name: 'Singapore',
    sales: 1908,
  },
  {
    name: 'Zurich',
    sales: 1398,
  },
];

export default function Home() {
  const [breakpoint, setBreakpoint] = useState<string>('');

  return (
    <>
      <Head>
        <title>Arkiva</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-24 flex h-screen w-full flex-col gap-4">
        <div className="flex w-full flex-col gap-4 bg-[#6E71F1] p-8 lg:flex-row">
          <KpiCard
            title="Total Income"
            metric="317,000"
            percentage="3,48"
            delta="increase"
          />
          <KpiCard
            title="Total Profit"
            metric="96,000"
            percentage="1,48"
            delta="increase"
          />
          <KpiCard
            title="Total Loss"
            metric="317,000"
            percentage="1,48"
            delta="decrease"
          />
          <KpiCard
            title="Total something"
            metric="23,317,000"
            percentage="100"
            delta="decrease"
          />
        </div>

        <div className="h-max w-full border p-8">
          <NoSSR />
        </div>
      </main>
    </>
  );
}
