import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button } from '@/components/ui/button';
import Sidebar from '@/components/molecules/Sidebar';
import GridLayout from '@/components/molecules/GridLayout';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Arkiva</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="h-screen max-w-[calc(100%-250px)] w-full ml-[250px] flex flex-col gap-4">
        <h2 className='w-full bg-blue-200'>hello</h2>
        <GridLayout />
      </main>
    </>
  );
}
